In [2]:
import tensorflow as tf
import numpy as np
import matplotlib
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input, Dense, InputLayer
import matplotlib.pyplot as plt
from tensorflow.keras import utils as np_utils

In [3]:
(X_treinamento, y_treinamento), (X_teste, y_teste) = mnist.load_data()

In [4]:
X_treinamento = X_treinamento.astype('float32') / 255
X_teste = X_teste.astype('float32') / 255

In [5]:
X_treinamento[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [6]:
y_treinamento

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
y_treinamento = np_utils.to_categorical(y_treinamento)
y_teste = np_utils.to_categorical(y_teste)

In [8]:
y_treinamento, y_treinamento[0]

(array([[0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.]]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]))

In [9]:
X_treinamento.shape

(60000, 28, 28)

In [10]:
X_treinamento = X_treinamento.reshape((len(X_treinamento), np.prod(X_treinamento.shape[1:])))
X_teste = X_teste.reshape((len(X_teste), np.prod(X_teste.shape[1:])))

In [11]:
X_treinamento.shape, X_teste.shape

((60000, 784), (10000, 784))

In [12]:
# 784 -> 32 -> 784
autoencoder = Sequential()
autoencoder.add(InputLayer(shape = (784,)))
autoencoder.add(Dense(units = 32, activation = 'relu'))
autoencoder.add(Dense(units = 784, activation = 'sigmoid'))
autoencoder.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │        25,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 784)            │        25,872 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 50,992 (199.19 KB)

 Trainable params: 50,992 (199.19 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
autoencoder.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])

In [14]:
autoencoder.fit(X_treinamento, X_treinamento, epochs = 50,
                batch_size=256, validation_data=(X_teste, X_teste))

Epoch 1/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0109 - loss: 0.3826 - val_accuracy: 0.0111 - val_loss: 0.1901
Epoch 2/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0106 - loss: 0.1808 - val_accuracy: 0.0117 - val_loss: 0.1540
Epoch 3/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0108 - loss: 0.1494 - val_accuracy: 0.0101 - val_loss: 0.1338
Epoch 4/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0108 - loss: 0.1313 - val_accuracy: 0.0103 - val_loss: 0.1207
Epoch 5/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0117 - loss: 0.1199 - val_accuracy: 0.0108 - val_loss: 0.1128
Epoch 6/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0119 - loss: 0.1124 - val_accuracy: 0.0120 - val_loss: 0.1070
Epoch 7/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0124 - loss: 0.1071 - val_accuracy: 0.0125 - val_loss: 0.1028
Epoch 8/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.0135 - loss: 0.1033 - val_accuracy: 0.

In [15]:
autoencoder.layers

[<Dense name=dense, built=True>, <Dense name=dense_1, built=True>]

In [16]:
dimensao_original = Input(shape=(784,))
camada_encoder = autoencoder.layers[0]
encoder = Model(dimensao_original, camada_encoder(dimensao_original))

In [17]:
treinamento_codificado = encoder.predict(X_treinamento)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 534us/step


In [18]:
teste_codificado = encoder.predict(X_teste)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step


In [19]:
treinamento_codificado.shape, teste_codificado.shape

((60000, 32), (10000, 32))

In [20]:
#sem redução de dimensionalidade
(784 + 10) / 2

397.0

In [21]:
X_treinamento.shape, X_teste.shape

((60000, 784), (10000, 784))

In [22]:
# 784 -> 397 -> 397 -> 10
c1 = Sequential()
c1.add(InputLayer(shape = (784,)))
c1.add(Dense(units = 397, activation='relu'))
c1.add(Dense(units = 397, activation='relu'))
c1.add(Dense(units = 10, activation='softmax'))

c1.compile(optimizer='adam', loss='categorical_crossentropy', metrics = ['accuracy'])

c1.fit(X_treinamento, y_treinamento, batch_size=256, epochs = 100,
       validation_data=(X_teste, y_teste))

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8551 - loss: 0.5279 - val_accuracy: 0.9572 - val_loss: 0.1348
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9661 - loss: 0.1133 - val_accuracy: 0.9694 - val_loss: 0.0956
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9795 - loss: 0.0646 - val_accuracy: 0.9761 - val_loss: 0.0735
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9870 - loss: 0.0430 - val_accuracy: 0.9764 - val_loss: 0.0736
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9907 - loss: 0.0302 - val_accuracy: 0.9741 - val_loss: 0.0808
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9926 - loss: 0.0240 - val_accuracy: 0.9797 - val_loss: 0.0707
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9941 - loss: 0.0180 - val_accuracy: 0.9805 - val_loss: 0.0657
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9957 - loss: 0.0136 - val_accu

In [23]:
#Com redução de dimensionalidade
(32 + 10) / 2

21.0

In [24]:
treinamento_codificado.shape, teste_codificado.shape

((60000, 32), (10000, 32))

In [25]:
# 32 -> 397 -> 397 -> 10
c1 = Sequential()
c1.add(InputLayer(shape = (32,)))
c1.add(Dense(units = 21, activation='relu'))
c1.add(Dense(units = 21, activation='relu'))
c1.add(Dense(units = 10, activation='softmax'))

c1.compile(optimizer='adam', loss='categorical_crossentropy', metrics = ['accuracy'])

c1.fit(treinamento_codificado, y_treinamento, batch_size=256, epochs = 100,
       validation_data=(teste_codificado, y_teste))

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3013 - loss: 2.8586 - val_accuracy: 0.7347 - val_loss: 0.8270
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7662 - loss: 0.7458 - val_accuracy: 0.8356 - val_loss: 0.5389
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - accuracy: 0.8385 - loss: 0.5241 - val_accuracy: 0.8685 - val_loss: 0.4351
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8695 - loss: 0.4340 - val_accuracy: 0.8850 - val_loss: 0.3807
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8832 - loss: 0.3867 - val_accuracy: 0.8949 - val_loss: 0.3460
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8949 - loss: 0.3530 - val_accuracy: 0.8992 - val_loss: 0.3235
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9001 - loss: 0.3292 - val_accuracy: 0.9093 - val_loss: 0.3003
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9044 - loss: 0.3175 - val_ac