In [50]:
import numpy as np
import rbm

In [51]:
rbm = rbm.RBM(num_visible= 6, num_hidden= 3)

In [52]:
#1 = assistiu o filme, 0 = não assistiu
base = np.array([[0, 1, 1, 1, 0, 1],
                 [1, 1, 0, 1, 1, 1],
                 [0, 1, 0, 1, 0, 1],
                 [0, 1, 1, 1, 0, 1],
                 [1, 1, 0, 1, 0, 1],
                 [1, 1, 0, 1, 1, 1],])

In [53]:
base.shape

(6, 6)

In [54]:
filmes = ["FreddyXJason", "O ultimo bourne", "Star trek",
          "Exterminador do futuro", "Norbit", "Star wars"]

In [55]:
rbm.train(base, max_epochs=5000)

Epoch 0: error is 8.96461732513312
Epoch 1: error is 8.399540822130465
Epoch 2: error is 8.061875236100123
Epoch 3: error is 7.570544579968675
Epoch 4: error is 7.155889638807066
Epoch 5: error is 7.031731796139191
Epoch 6: error is 6.241236370058386
Epoch 7: error is 6.641046631491662
Epoch 8: error is 5.961050450998675
Epoch 9: error is 5.8293983555866395
Epoch 10: error is 5.838063510301148
Epoch 11: error is 5.56176922668685
Epoch 12: error is 5.3624643974341195
Epoch 13: error is 5.334587966381419
Epoch 14: error is 5.1826049090609985
Epoch 15: error is 4.869445335217378
Epoch 16: error is 4.761776705539455
Epoch 17: error is 4.605430759712433
Epoch 18: error is 4.583846630494374
Epoch 19: error is 4.571453517175281
Epoch 20: error is 4.774413331515372
Epoch 21: error is 4.559960191893409
Epoch 22: error is 4.590434750971718
Epoch 23: error is 4.556645123206106
Epoch 24: error is 4.290684067421615
Epoch 25: error is 4.571818344605888
Epoch 26: error is 4.267613678348781
Epoch 27: 

In [56]:
rbm.weights, rbm.weights.shape

(array([[ 0.84209076, -1.13374661, -1.06663183,  0.33985329],
        [ 1.69027647,  1.99902434,  2.11124069, -7.23417402],
        [ 3.55428919,  1.18409804,  1.22321984,  2.0438871 ],
        [-0.22849547, -5.56146349, -5.75088954,  5.89814686],
        [ 3.55949319,  1.21408858,  1.17016702,  2.06893361],
        [ 0.13849805,  0.39441433,  0.42337215, -5.99694531],
        [ 3.58191167,  1.17373637,  1.20413687,  2.02576263]]),
 (7, 4))

In [57]:
usuario1 = np.array([[0, 1, 0, 1, 0, 0]])

In [58]:
#verificando a saída da camada escondida para o usuário1
rbm.run_visible(usuario1)

array([[1., 1., 1.]])

In [59]:
#gerar a recomendação e exibir as probabilidades para cada filme
camada_escondida = np.array([[1, 1, 1]])
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[0., 1., 0., 1., 0., 1.]])

In [60]:
#recomendação de filmes para o usuario1
for i in range(len(usuario1[0])):
    if usuario1[0, i] == 0 and recomendacao[0, i] == 1:
        print(filmes[i])

Star wars
