In [27]:
import numpy as np
import rbm

In [28]:
rbm = rbm.RBM(num_visible= 6, num_hidden= 2)

In [29]:
#1 = assistiu o filme, 0 = não assistiu
base = np.array([[1, 1, 1, 0, 0, 0],
                 [1, 0, 1, 0, 0, 0],
                 [1, 1, 1, 0, 0, 0],
                 [0, 0, 1, 1, 1, 1],
                 [0, 0, 1, 1, 0, 1],
                 [0, 0, 1, 1, 0, 1],])

In [30]:
base.shape

(6, 6)

In [31]:
filmes = ["A bruxa", "Invocação do mal", "O chamado",
          "Se beber não case", "Gente grande", "American pie"]

In [32]:
rbm.train(base, max_epochs=5000)

Epoch 0: error is 9.138815182598993
Epoch 1: error is 8.916332653841852
Epoch 2: error is 8.750160559384234
Epoch 3: error is 8.550756776607875
Epoch 4: error is 8.515665926940658
Epoch 5: error is 8.292929953340723
Epoch 6: error is 8.277025527779406
Epoch 7: error is 8.194023371678641
Epoch 8: error is 8.048543075330068
Epoch 9: error is 7.9600901824831976
Epoch 10: error is 7.845619852197379
Epoch 11: error is 7.710424008674977
Epoch 12: error is 7.720868998914004
Epoch 13: error is 7.801372146911252
Epoch 14: error is 7.405250870419798
Epoch 15: error is 7.634091575129026
Epoch 16: error is 7.533469828165244
Epoch 17: error is 7.251602420267077
Epoch 18: error is 7.276358488902988
Epoch 19: error is 7.2431018356476145
Epoch 20: error is 7.403028769140188
Epoch 21: error is 7.209377113382294
Epoch 22: error is 7.2486786923447974
Epoch 23: error is 7.053419730339634
Epoch 24: error is 7.043392632958589
Epoch 25: error is 7.1738758176037605
Epoch 26: error is 7.028699709289954
Epoch 2

In [33]:
rbm.weights, rbm.weights.shape

(array([[ 2.47071906,  2.36706302,  0.40776349],
        [-0.98746544, -3.26479337,  7.9121241 ],
        [ 0.16430139, -7.20843594,  3.28233416],
        [ 4.95075886,  3.94875051,  1.90443671],
        [ 0.91083682,  3.65663704, -8.21092755],
        [-1.33116591,  0.6261765 , -4.53973313],
        [ 0.91618575,  3.65251787, -8.21353573]]),
 (7, 3))

In [34]:
usuario1 = np.array([[1, 1, 0, 1, 0, 0]])
usuario2 = np.array([[0, 0, 0, 1, 1, 0]])

In [35]:
#neuronio1 = filme de comedia, neuronio2 = filme de terror
rbm.run_visible(usuario1)

array([[0., 1.]])

In [36]:
rbm.run_visible(usuario2)

array([[1., 0.]])

In [37]:
camada_escondida = np.array([[1, 0]])
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[0., 0., 1., 1., 0., 1.]])

In [39]:
#recomendação de filmes para o usuario1
for i in range(len(usuario1[0])):
    if usuario2[0, i] == 0 and recomendacao[0, i] == 1:
        print(filmes[i])

O chamado
American pie
